#define PIN_GAS_PEDAL A0
#define PIN_BATTERY_VOLTAGE A1

#define PIN_CW 6
#define PIN_CCW 5

#define PIN_SWITCH_FORWARDS 10
#define PIN_SWITCH_BACKWARDS 11

#define GAS_VALUE_MIN 446
#define GAS_VALUE_MAX 490 //510

#define BATTERY_READING_12V 670
#define BATTERY_READING_6V 331

#define BATTERY_VOLTAGE_MIN 11

#define SPEED_MIN 0
#define SPEED_MAX_DIRECTION_CHANGE 15
#define SPEED_MAX_FORWARDS 255
#define SPEED_MAX_BACKWARDS 182
#define SPEED_MAX_BATTERY_PROTECTION 180
#define SPEED_CHANGE_PACE_DEFAULT 10
